x-shared-service: &shared-service
  env_file:
    - .env
  restart: unless-stopped
  networks:
    - urls-network

x-shared-service-no-env: &shared-service-no-env
  restart: unless-stopped
  networks:
    - urls-network

services:
  db:
    image: postgres:15-alpine
    <<: *shared-service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: urls:backend
    container_name: urls-backend
    <<: *shared-service
    volumes:
      - ./Backend/config:/app/config

  frontend:
    image: urls:frontend
    container_name: urls-frontend
    <<: *shared-service
  redis:
    image: redis:7-alpine
    <<: *shared-service-no-env
    environment:
      REDIS_PASSWORD: urls123
    command: redis-server --requirepass urls123

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    <<: *shared-service-no-env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

    

volumes:
  postgres_data:

networks:
  urls-network:
    driver: bridge
