x-shared-service: &shared-service
  env_file:
    - .env
  restart: unless-stopped
  networks:
    - urls-network

x-shared-service-no-env: &shared-service-no-env
  restart: unless-stopped
  networks:
    - urls-network

services:
  db:
    image: postgres:15-alpine
    <<: *shared-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: urls123
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: luongnguyenminhan/url-shortener:backend
    container_name: urls-backend
    <<: *shared-service
    labels:
      - "logging=promtail"
      - "job=urls-backend"
    volumes:
      - ./Backend/config:/app/config

  frontend:
    image: luongnguyenminhan/url-shortener:frontend
    container_name: urls-frontend
    <<: *shared-service
    labels:
      - "logging=promtail"
      - "job=urls-frontend"
  redis:
    image: redis:7-alpine
    <<: *shared-service-no-env
    environment:
      REDIS_PASSWORD: urls123
    labels:
      - "logging=promtail"
      - "job=urls-redis"
    command: redis-server --requirepass urls123

  adminer:
    image: adminer:latest
    <<: *shared-service-no-env
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8084:80"
    <<: *shared-service-no-env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - adminer
    profiles:
      - prod


volumes:
  postgres_data:

networks:
  urls-network:
    driver: bridge
